services:
  - type: web
    name: pdf-extraction-backend
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: LOG_LEVEL
        value: INFO
      - key: MAX_FILE_SIZE
        value: 52428800
      - key: UPLOAD_DIR
        value: /tmp/uploads
      - key: OUTPUT_DIR
        value: /tmp/outputs
      - key: CORS_ORIGINS
        value: '["https://your-frontend.vercel.app"]'
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true
